SRC_DIR := $(dir $(lastword $(MAKEFILE_LIST)))

EXTRA_INCL += -I$(SRC_DIR)

MY_TARGETS = $(A)test_stringref $(A)test_blobref $(A)test_binarysearch

EXTRA_CLEAN += $(MY_TARGETS)

include Makefile.sub

all: $(MY_TARGETS)


$(A)test_stringref: $(O)test_stringref.o
	$(LINK)

$(A)test_blobref: $(O)test_blobref.o
	$(LINK)

$(A)test_binarysearch: $(O)test_binarysearch.o
	$(LINK)

