SRC_DIR := $(dir $(lastword $(MAKEFILE_LIST)))

EXTRA_INCL += -I$(SRC_DIR)test_bfslookup

# $(A)test_smallstring

MY_TARGETS = $(A)test_stringhash $(A)test_stringreplace $(A)test_trim $(A)test_stringtokenizer	\
		$(A)test_blobref $(A)test_binarysearch $(A)test_bfslookup		\
		$(A)test_glob  $(A)test_myalign $(A)test_mynarrow $(A)test_signalguard		\
		$(A)test_base64

EXTRA_CLEAN += $(MY_TARGETS)

include Makefile.sub

all: $(MY_TARGETS)

#$(A)test_smallstring: $(O)test_smallstring.o
#	$(LINK)

$(A)test_stringhash: $(O)test_stringhash.o
	$(LINK)

$(A)test_stringreplace: $(O)test_stringreplace.o
	$(LINK)

$(A)test_trim: $(O)test_trim.o
	$(LINK)

$(A)test_stringtokenizer: $(O)test_stringtokenizer.o
	$(LINK)

$(A)test_blobref: $(O)test_blobref.o
	$(LINK)

$(A)test_binarysearch: $(O)test_binarysearch.o
	$(LINK)

$(A)test_bfslookup: $(O)test_bfslookup.o
	$(LINK)

$(A)test_glob: $(O)test_glob.o $(O)myglob.o
	$(LINK)

$(A)test_myalign: $(O)test_myalign.o
	$(LINK)

$(A)test_mynarrow: $(O)test_mynarrow.o
	$(LINK)

$(A)test_signalguard: $(O)test_signalguard.o $(O)signalguard.o
	$(LINK)

$(A)test_base64: $(O)test_base64.o $(O)base64.o
	$(LINK)

$(A)test_idgenerator: $(O)test_idgenerator.o $(O)idgenerator.o $(O)mytime.o
	$(LINK)

