SRC_DIR := $(dir $(lastword $(MAKEFILE_LIST)))

#EXTRA_INCL += -I$(SRC_DIR)

EXTRA_CLEAN += $(A)db_net

include Makefile.sub

all: $(A)db_net

$(A)db_net: $(O)db_net.o	\
			$(O)directorytableloader.o $(O)myglob.o					\
			$(O)pair.o $(O)pairblob.o $(O)mytime.o					\
			$(O)disktable.o $(O)mmapfile.o $(O)filemeta.o $(O)filemetablob.o	\
												\
			$(O)pollselector.o $(O)redisprotocol.o $(O)keyvalueworker.o $(O)sockets.o
	$(LINK)

