SRC_DIR := $(dir $(lastword $(MAKEFILE_LIST)))

#EXTRA_INCL += -I$(SRC_DIR)

include Makefile.sub

# ===========================================================

ifeq ($(UNAME), Linux)

ifeq ($(IOURING_ENGINE), YES)
# add io_uring support...
all: $(O)iouringengine.o

EXTRA_CLEAN += $(O)iouringengine.o
endif

endif

# ===========================================================

