SRC_DIR := $(dir $(lastword $(MAKEFILE_LIST)))

EXTRA_INCL += -I$(SRC_DIR)

#EXTRA_CLEAN +=

include Makefile.sub

all:	\
	$(O)pair.o	\
	$(O)vectorlist.o $(O)linklist.o $(O)skiplist.o	\
	$(O)pairvector.o				\
	$(O)unrolledlinklist.o $(O)unrolledskiplist.o

