SRC_DIR := $(dir $(lastword $(MAKEFILE_LIST)))

EXTRA_INCL += -I$(SRC_DIR)

MY_TARGETS = $(A)test_pair $(A)test_list $(A)test_multi_table $(A)test_file $(A)test_idgenerator

#$(A)test_duallist

EXTRA_CLEAN += $(MY_TARGETS)

include Makefile.sub

all: $(MY_TARGETS)


PAIR_OBJ = $(O)pair.o $(O)pairblob.o $(O)mytime.o


$(A)test_pair: $(O)test_pair.o $(PAIR_OBJ)
	$(LINK)

$(A)test_list: $(O)test_list.o $(PAIR_OBJ)			\
		$(O)vectorlist.o $(O)linklist.o $(O)skiplist.o
	$(LINK)

$(A)test_multi_table: $(O)test_multi_table.o $(PAIR_OBJ)	\
		$(O)vectorlist.o
	$(LINK)

$(A)test_file: $(O)test_file.o $(PAIR_OBJ)			\
		$(O)vectorlist.o $(O)linklist.o $(O)skiplist.o	\
		$(O)filemetablob.o
	$(LINK)

$(A)test_idgenerator: $(O)test_idgenerator.o $(O)idgeneratorts.o $(O)idgeneratordate.o $(O)mytime.o
		$(LINK)

