SRC_DIR := $(dir $(lastword $(MAKEFILE_LIST)))

EXTRA_INCL += -I$(SRC_DIR)

MY_TARGETS = $(A)test_pair $(A)test_pairvector $(A)test_list $(A)test_multi_list $(A)test_file

EXTRA_CLEAN += $(MY_TARGETS)

include Makefile.sub

all: $(MY_TARGETS)


PAIR_OBJ = $(O)pair.o $(O)mytime.o $(O)logger.o


$(A)test_pair: $(O)test_pair.o $(PAIR_OBJ)
	$(LINK)

$(A)test_pairvector: $(O)test_pairvector.o $(PAIR_OBJ)		\
		$(O)test_pairvector.o
	$(LINK)

$(A)test_list: $(O)test_list.o $(PAIR_OBJ)			\
		$(O)vectorlist.o $(O)linklist.o $(O)skiplist.o	\
		$(O)unrolledlinklist.o $(O)unrolledskiplist.o
	$(LINK)

$(A)test_multi_list: $(O)test_multi_list.o $(PAIR_OBJ)	\
		$(O)vectorlist.o
	$(LINK)

$(A)test_file: $(O)test_file.o $(PAIR_OBJ)			\
		$(O)vectorlist.o $(O)linklist.o $(O)skiplist.o	\
		$(O)unrolledlinklist.o $(O)unrolledskiplist.o	\
		$(O)filemetablob.o
	$(LINK)


