SRC_DIR := $(dir $(lastword $(MAKEFILE_LIST)))

EXTRA_INCL += -I$(SRC_DIR)

MY_TARGETS = $(A)test_pair $(A)test_list

#$(A)test_duallist

EXTRA_CLEAN += $(MY_TARGETS)

include Makefile.sub

all: $(MY_TARGETS)


PAIR_OBJ = $(O)pair.o $(O)pairblob.o $(O)mytime.o


$(A)test_pair: $(O)test_pair.o $(PAIR_OBJ)
	$(LINK)

$(A)test_list: $(O)test_list.o $(PAIR_OBJ)	\
		$(O)vectorlist.o $(O)linklist.o $(O)skiplist.o
	$(LINK)

