SRC_DIR := $(dir $(lastword $(MAKEFILE_LIST)))

EXTRA_INCL += -I$(SRC_DIR)

#EXTRA_CLEAN +=

include Makefile.sub

all: $(O)mytime.o $(O)myglob.o $(O)myfs.o $(O)mmapfile.o $(O)signalguard.o $(O)base64.o $(O)myprocess.o $(O)idgenerator.o $(O)murmur_hash_64a.o $(O)hyperloglog.o


