/* C++ code produced by gperf version 3.3 */
/* Command-line: gperf --multiple-iterations=100  */
/* Computed positions: -k'1-5,8' */

#if !((' ' == 32) && ('!' == 33) && ('"' == 34) && ('#' == 35) \
      && ('%' == 37) && ('&' == 38) && ('\'' == 39) && ('(' == 40) \
      && (')' == 41) && ('*' == 42) && ('+' == 43) && (',' == 44) \
      && ('-' == 45) && ('.' == 46) && ('/' == 47) && ('0' == 48) \
      && ('1' == 49) && ('2' == 50) && ('3' == 51) && ('4' == 52) \
      && ('5' == 53) && ('6' == 54) && ('7' == 55) && ('8' == 56) \
      && ('9' == 57) && (':' == 58) && (';' == 59) && ('<' == 60) \
      && ('=' == 61) && ('>' == 62) && ('?' == 63) && ('A' == 65) \
      && ('B' == 66) && ('C' == 67) && ('D' == 68) && ('E' == 69) \
      && ('F' == 70) && ('G' == 71) && ('H' == 72) && ('I' == 73) \
      && ('J' == 74) && ('K' == 75) && ('L' == 76) && ('M' == 77) \
      && ('N' == 78) && ('O' == 79) && ('P' == 80) && ('Q' == 81) \
      && ('R' == 82) && ('S' == 83) && ('T' == 84) && ('U' == 85) \
      && ('V' == 86) && ('W' == 87) && ('X' == 88) && ('Y' == 89) \
      && ('Z' == 90) && ('[' == 91) && ('\\' == 92) && (']' == 93) \
      && ('^' == 94) && ('_' == 95) && ('a' == 97) && ('b' == 98) \
      && ('c' == 99) && ('d' == 100) && ('e' == 101) && ('f' == 102) \
      && ('g' == 103) && ('h' == 104) && ('i' == 105) && ('j' == 106) \
      && ('k' == 107) && ('l' == 108) && ('m' == 109) && ('n' == 110) \
      && ('o' == 111) && ('p' == 112) && ('q' == 113) && ('r' == 114) \
      && ('s' == 115) && ('t' == 116) && ('u' == 117) && ('v' == 118) \
      && ('w' == 119) && ('x' == 120) && ('y' == 121) && ('z' == 122) \
      && ('{' == 123) && ('|' == 124) && ('}' == 125) && ('~' == 126))
/* The character set is not based on ISO-646.  */
#error "gperf generated tables don't work with this execution character set. Please report a bug to <bug-gperf@gnu.org>."
#endif


/*
cat	\
	net/worker/keyvaluecommands/gperf/head.gperf		\
	net/worker/keyvaluecommands/gperf/cmd_*.gperf		\
	net/worker/keyvaluecommands/gperf/foot.gperf		| \
	grep -v '^$'						| \
	gperf --multiple-iterations=100 > net/worker/keyvaluecommands/gperf.h
seems multiple-iterations=100 have same result as 1024
*/
#include <string_view>
#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wconversion"
#endif
namespace net::worker::commands::gperf{
struct data{
	const char	*name;
	const char	*group;
	void		*ptr;
};
enum
  {
    TOTAL_KEYWORDS = 923,
    MIN_WORD_LENGTH = 1,
    MAX_WORD_LENGTH = 19,
    MIN_HASH_VALUE = 1,
    MAX_HASH_VALUE = 3124
  };

/* maximum key range = 3124, duplicates = 0 */

class CommandPerfectHash
{
private:
  static inline unsigned int hash (const char *str, size_t len);
public:
  static struct data *in_word_set (const char *str, size_t len);
};

inline unsigned int
CommandPerfectHash::hash (const char *str, size_t len)
{
  static unsigned short asso_values[] =
    {
      3125, 3125, 3125, 3125, 3125, 3125, 3125, 3125, 3125, 3125,
      3125, 3125, 3125, 3125, 3125, 3125, 3125, 3125, 3125, 3125,
      3125, 3125, 3125, 3125, 3125, 3125, 3125, 3125, 3125, 3125,
      3125, 3125, 3125, 3125, 3125,    2, 3125, 3125, 3125, 3125,
      3125, 3125, 3125, 3125, 3125, 3125, 3125,    0, 3125, 1201,
      1065,  599,  479,  471,  848, 3125, 1004, 3125, 3125,    0,
      3125, 3125, 3125, 3125, 3125,  372,    0,    1,  613,    5,
        64,  670,  683,    0,  529,    0,  507,   87,  757,  124,
       891,   42,    0,  303,   28,  457,  627,    2,    1, 1112,
         2,    2, 3125, 3125, 3125,   13,    0,    0,    0,   62,
         6,    4,    3,  155,  255,   62, 1413,    0,  383,   17,
       245,  106,  485,  322,    0,    5,   28,  377,  219,    7,
        57, 1599,   10,    5, 3125, 3125, 3125, 3125, 3125, 3125,
      3125, 3125, 3125, 3125, 3125, 3125, 3125, 3125, 3125, 3125,
      3125, 3125, 3125, 3125, 3125, 3125, 3125, 3125, 3125, 3125,
      3125, 3125, 3125, 3125, 3125, 3125, 3125, 3125, 3125, 3125,
      3125, 3125, 3125, 3125, 3125, 3125, 3125, 3125, 3125, 3125,
      3125, 3125, 3125, 3125, 3125, 3125, 3125, 3125, 3125, 3125,
      3125, 3125, 3125, 3125, 3125, 3125, 3125, 3125, 3125, 3125,
      3125, 3125, 3125, 3125, 3125, 3125, 3125, 3125, 3125, 3125,
      3125, 3125, 3125, 3125, 3125, 3125, 3125, 3125, 3125, 3125,
      3125, 3125, 3125, 3125, 3125, 3125, 3125, 3125, 3125, 3125,
      3125, 3125, 3125, 3125, 3125, 3125, 3125, 3125, 3125, 3125,
      3125, 3125, 3125, 3125, 3125, 3125, 3125, 3125, 3125, 3125,
      3125, 3125, 3125, 3125, 3125, 3125, 3125, 3125, 3125, 3125,
      3125, 3125, 3125, 3125, 3125, 3125, 3125
    };
  unsigned int hval = len;

  switch (hval)
    {
      default:
        hval += asso_values[static_cast<unsigned char>(str[7])];
#if (defined __cplusplus && (__cplusplus >= 201703L || (__cplusplus >= 201103L && defined __clang__ && __clang_major__ + (__clang_minor__ >= 9) > 3))) || (defined __STDC_VERSION__ && __STDC_VERSION__ >= 202000L && ((defined __GNUC__ && __GNUC__ >= 10) || (defined __clang__ && __clang_major__ >= 9)))
      [[fallthrough]];
#elif (defined __GNUC__ && __GNUC__ >= 7) || (defined __clang__ && __clang_major__ >= 10)
      __attribute__ ((__fallthrough__));
#endif
      /*FALLTHROUGH*/
      case 7:
      case 6:
      case 5:
        hval += asso_values[static_cast<unsigned char>(str[4]+1)];
#if (defined __cplusplus && (__cplusplus >= 201703L || (__cplusplus >= 201103L && defined __clang__ && __clang_major__ + (__clang_minor__ >= 9) > 3))) || (defined __STDC_VERSION__ && __STDC_VERSION__ >= 202000L && ((defined __GNUC__ && __GNUC__ >= 10) || (defined __clang__ && __clang_major__ >= 9)))
      [[fallthrough]];
#elif (defined __GNUC__ && __GNUC__ >= 7) || (defined __clang__ && __clang_major__ >= 10)
      __attribute__ ((__fallthrough__));
#endif
      /*FALLTHROUGH*/
      case 4:
        hval += asso_values[static_cast<unsigned char>(str[3])];
#if (defined __cplusplus && (__cplusplus >= 201703L || (__cplusplus >= 201103L && defined __clang__ && __clang_major__ + (__clang_minor__ >= 9) > 3))) || (defined __STDC_VERSION__ && __STDC_VERSION__ >= 202000L && ((defined __GNUC__ && __GNUC__ >= 10) || (defined __clang__ && __clang_major__ >= 9)))
      [[fallthrough]];
#elif (defined __GNUC__ && __GNUC__ >= 7) || (defined __clang__ && __clang_major__ >= 10)
      __attribute__ ((__fallthrough__));
#endif
      /*FALLTHROUGH*/
      case 3:
        hval += asso_values[static_cast<unsigned char>(str[2])];
#if (defined __cplusplus && (__cplusplus >= 201703L || (__cplusplus >= 201103L && defined __clang__ && __clang_major__ + (__clang_minor__ >= 9) > 3))) || (defined __STDC_VERSION__ && __STDC_VERSION__ >= 202000L && ((defined __GNUC__ && __GNUC__ >= 10) || (defined __clang__ && __clang_major__ >= 9)))
      [[fallthrough]];
#elif (defined __GNUC__ && __GNUC__ >= 7) || (defined __clang__ && __clang_major__ >= 10)
      __attribute__ ((__fallthrough__));
#endif
      /*FALLTHROUGH*/
      case 2:
        hval += asso_values[static_cast<unsigned char>(str[1])];
#if (defined __cplusplus && (__cplusplus >= 201703L || (__cplusplus >= 201103L && defined __clang__ && __clang_major__ + (__clang_minor__ >= 9) > 3))) || (defined __STDC_VERSION__ && __STDC_VERSION__ >= 202000L && ((defined __GNUC__ && __GNUC__ >= 10) || (defined __clang__ && __clang_major__ >= 9)))
      [[fallthrough]];
#elif (defined __GNUC__ && __GNUC__ >= 7) || (defined __clang__ && __clang_major__ >= 10)
      __attribute__ ((__fallthrough__));
#endif
      /*FALLTHROUGH*/
      case 1:
        hval += asso_values[static_cast<unsigned char>(str[0])];
        break;
    }
  return hval;
}

#if (defined __GNUC__ && __GNUC__ + (__GNUC_MINOR__ >= 6) > 4) || (defined __clang__ && __clang_major__ >= 3)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif
static struct data wordlist[] =
  {
    {""},
    {";",		"REM"},
    {"//",		"REM"},
    {"#",		"REM"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""},
    {"rbadd",		"RBADD"},
    {""}, {""},
    {"bfadd",		"BFADD"},
    {""},
    {"rsadd",		"RSADD"},
    {"sadd",	"SADD"},
    {""}, {""},
    {"rem",		"REM"},
    {"ssadd",		"SSADD"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {"ssaddmget",	"SSADDMGET"},
    {""}, {""}, {""}, {""},
    {"EXIT",		"EXIT"},
    {""},
    {"set",		"SET"},
    {""}, {""},
    {"ssmerge",	"SSMERGE"},
    {""}, {""},
    {"IXTRANGEFLEX",		"IXTRANGEFLEX_UTF8"},
    {""},
    {"IXTRANGESTRICT",		"IXTRANGESTRICT_UTF8"},
    {"tdadd",			"TDADD"},
    {"IXTRANGEFLEX_BIN",	"IXTRANGEFLEX_BIN"},
    {"IXTRANGEFLEX_UTF8",	"IXTRANGEFLEX_UTF8"},
    {"IXTRANGESTRICT_BIN",	"IXTRANGESTRICT_BIN"},
    {"IXTRANGESTRICT_UTF8",	"IXTRANGESTRICT_UTF8"},
    {""}, {""},
    {"ssaddget",	"SSADDGET"},
    {""},
    {"mset",		"MSET"},
    {"ssaddgetall",	"SSADDGETALL"},
    {""},
    {"tdmean",			"TDMEAN"},
    {"XREXPIRE",	"XREXPIRE"},
    {""},
    {"XREXPIREAT",	"XREXPIREAT"},
    {""}, {""},
    {"tdmerge",		"TDMERGE"},
    {""},
    {"test",	"TEST"},
    {"cas",	"CAS"},
    {"cad",	"CAD"},
    {""}, {""},
    {"cbfrem",		"CBFREM"},
    {"cbfadd",		"CBFADD"},
    {"decr",		"DECR"},
    {"acadd",			"ACADD_UTF8"},
    {"cbfreserve",	"CBFRESERVE"},
    {""},
    {"cfadd",		"CFADD"},
    {"cbfdecr",	"CBFREM"},
    {""},
    {"cbfdecrby",	"CBFREM"},
    {"dbsize",		"DBSIZE"},
    {"size",		"STRLEN"},
    {"ireserve",	"IRESERVE"},
    {""},
    {"size_of",	"SIZEOF"},
    {"xrdel",		"XRDEL"},
    {""},
    {"cfmrem",		"CFMREM"},
    {"cfmadd",		"CFMADD"},
    {"cmsrem",		"CMSREM"},
    {"cmsadd",		"CMSADD"},
    {"REM",		"REM"},
    {""},
    {"cmsreserve",	"CMSRESERVE"},
    {""},
    {"IXTREM",		"IXMREM"},
    {"cmsdecr",	"CMSREM"},
    {"IXMRANGE",	"IXMRANGE"},
    {"cmsdecrby",	"CMSREM"},
    {"iset",		"ISET"},
    {"bitset",		"BITSET"},
    {"IXMRANGEFLEX",	"IXMRANGEFLEX"},
    {"isetall",	"ISETALL"},
    {"IXMRANGESTRICT",	"IXMRANGESTRICT"},
    {""}, {""},
    {"acadd_utf8",		"ACADD_UTF8"},
    {""},
    {"tdsize",			"TDSIZE"},
    {"bitmax",		"BITMAX"},
    {""},
    {"time",		"TIME"},
    {""},
    {"tdaddweight",		"TDADDWEIGHT"},
    {""}, {""}, {""},
    {"BITMAX",		"BITMAX"},
    {""}, {""},
    {"TIME",		"TIME"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {"tdmergecap",		"TDMERGECAPACITY"},
    {""},
    {"xrfirst",	"XRFIRST"},
    {"CBFREM",		"CBFREM"},
    {""},
    {"tdmergecapacity",	"TDMERGECAPACITY"},
    {""},
    {"CBFRESERVE",	"CBFRESERVE"},
    {"decrby",		"DECR"},
    {""},
    {"bitmset",	"BITSET"},
    {"acadd_bin",		"ACADD_BIN"},
    {""},
    {"ixmrem",		"IXMREM"},
    {"ixmadd",		"IXMADD"},
    {""},
    {"ixmrange",	"IXMRANGE"},
    {"maxkeysize",	"MAXKEYSIZE"},
    {"BITMSET",	"BITSET"},
    {"ixmdel",		"IXMREM"},
    {"ixmrangeflex",	"IXMRANGEFLEX"},
    {""},
    {"ixmrangestrict",	"IXMRANGESTRICT"},
    {"exit",		"EXIT"},
    {"ixtrem",		"IXMREM"},
    {"ixtadd",			"IXTADD_UTF8"},
    {"IXMREM",		"IXMREM"},
    {""},
    {"decrlimit",	"DECRLIMIT"},
    {"ixtadd_bin",		"IXTADD_BIN"},
    {"ixtdel",		"IXMREM"},
    {"ixtrangeflex",		"IXTRANGEFLEX_UTF8"},
    {""},
    {"ixtrangestrict",		"IXTRANGESTRICT_UTF8"},
    {"msetnx",		"MSETNX"},
    {"ixtrangeflex_bin",	"IXTRANGEFLEX_BIN"},
    {"ixtrangeflex_utf8",	"IXTRANGEFLEX_UTF8"},
    {"ixtrangestrict_bin",	"IXTRANGESTRICT_BIN"},
    {"ixtrangestrict_utf8",	"IXTRANGESTRICT_UTF8"},
    {""}, {""},
    {"bgsave",			"SAVE"},
    {""},
    {"acrange",		"ACRANGE"},
    {""}, {""},
    {"acrangeall",		"ACRANGEALL"},
    {""}, {""}, {""},
    {"acrangeall_bin",		"ACRANGEALL"},
    {"acrangeall_utf8",	"ACRANGEALL"},
    {""},
    {"cbfremcount",	"CBFREMCOUNT"},
    {"cbfaddcount",	"CBFADDCOUNT"},
    {"mgadd",		"MGADD"},
    {""}, {""},
    {"get",		"GET"},
    {"ssmget",		"SSMGET"},
    {"acrange_bin",		"ACRANGE"},
    {"acrange_utf8",		"ACRANGE"},
    {""}, {""},
    {"CBFINCR",	"CBFADD"},
    {""},
    {"CBFINCRBY",	"CBFADD"},
    {"getrange",	"GETRANGE"},
    {""},
    {"getset",		"GETSET"},
    {"getdel",		"GETDEL"},
    {""},
    {"cmsremcount",	"CMSREMCOUNT"},
    {"cmsaddcount",	"CMSADDCOUNT"},
    {""}, {""},
    {"mget",		"MGET"},
    {"command",	"COMMAND"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {"XRMIN",		"XRMIN"},
    {"mgaddget",	"MGADDGET"},
    {""}, {""}, {""},
    {"CFMREM",		"CFMREM"},
    {""},
    {"tdmin",			"TDMIN"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {"save",			"SAVE"},
    {""}, {""},
    {"vadd",			"VADD"},
    {""}, {""}, {""}, {""},
    {"cbfincr",	"CBFADD"},
    {""},
    {"cbfincrby",	"CBFADD"},
    {""},
    {"vrem",			"VREM"},
    {""}, {""},
    {"xrmin",		"XRMIN"},
    {"getx",		"XNGET"},
    {""}, {""}, {""}, {""},
    {"iget",		"IGET"},
    {"bitget",		"BITGET"},
    {"rand",		"RANDOM"},
    {"igetall",	"IGETALL"},
    {""}, {""},
    {"cmsincr",	"CMSADD"},
    {"rbreserve",	"RBRESERVE"},
    {"cmsincrby",	"CMSADD"},
    {""},
    {"bfreserve",	"BFRESERVE"},
    {"CBFREMCOUNT",	"CBFREMCOUNT"},
    {"rsreserve",	"RSRESERVE"},
    {""}, {""}, {""},
    {"igetvals",	"IGETVALS"},
    {"ssreserve",	"SSRESERVE"},
    {"mrand",		"MRANDOM"},
    {""},
    {"mrandom",	"MRANDOM"},
    {"georem",		"GEOREM"},
    {"geoadd",		"GEOADD"},
    {""}, {""}, {""}, {""},
    {"geodel",		"GEOREM"},
    {""}, {""}, {""}, {""}, {""}, {""},
    {"mhadd",		"MHADD"},
    {"geoscore",	"GEOGET"},
    {"geodecode",	"GEODECODE"},
    {""}, {""}, {""}, {""},
    {"tdreserve",		"TDRESERVE"},
    {""},
    {"hset",		"HSET"},
    {""}, {""}, {""},
    {"ixmget",		"IXMGET"},
    {""}, {""}, {""}, {""}, {""},
    {"COMMAND",	"COMMAND"},
    {"vsim",			"VSIM"},
    {""}, {""}, {""},
    {"ixtget",		"IXMGET"},
    {"tdmedian",		"TDMEDIAN"},
    {""},
    {"SIZE",		"STRLEN"},
    {""},
    {"acrem",			"ACREM_UTF8"},
    {"SIZE_OF",	"SIZEOF"},
    {""},
    {"cfrem",		"CFREM"},
    {""}, {""}, {""}, {""}, {""},
    {"cfreserve",	"CFRESERVE"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {"xndel",		"XNDEL"},
    {""}, {""}, {""},
    {"vmdist",			"VMDISTANCE"},
    {"SET",		"SET"},
    {"ISET",		"ISET"},
    {""},
    {"cbfmcount",	"CBFMCOUNT"},
    {"ISETALL",	"ISETALL"},
    {""}, {""}, {""}, {""}, {""},
    {"acrem_utf8",		"ACREM_UTF8"},
    {"move",		"RENAME"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""},
    {"cmsmcount",	"CMSMCOUNT"},
    {""}, {""}, {""},
    {"maxvalsize",	"MAXVALSIZE"},
    {""},
    {"ixmremove",	"IXMREM"},
    {"TEST",	"TEST"},
    {"bitmget",	"BITMGET"},
    {""}, {""}, {""},
    {"incr",		"INCR"},
    {""},
    {"XRFIRST",	"XRFIRST"},
    {""}, {""},
    {"ixtremove",	"IXMREM"},
    {"xnfirst",	"XNFIRST"},
    {""}, {""},
    {"acrem_bin",		"ACREM_BIN"},
    {"ixhrem",		"IXMREM"},
    {"ixhadd",		"IXHADD_UTF8"},
    {"IRESERVE",	"IRESERVE"},
    {""}, {""},
    {"ixhadd_bin",	"IXHADD_BIN"},
    {"ixhdel",		"IXMREM"},
    {"geoencode",	"GEOENCODE"},
    {""}, {""}, {""},
    {"rbcount",	"RBCOUNT"},
    {"reset",		"RESET"},
    {"del",		"DEL"},
    {""}, {""}, {""}, {""},
    {"BITSET",		"BITSET"},
    {"sum",		"SUM"},
    {"sladd",		"SLADD"},
    {""}, {""}, {""}, {""},
    {"select",		"SELECT"},
    {""},
    {"vget",			"VGET"},
    {""},
    {"IXTADD",			"IXTADD_UTF8"},
    {"hexists",	"HEXISTS"},
    {""},
    {"ixmmget",	"IXMMGET"},
    {"IXTADD_BIN",		"IXTADD_BIN"},
    {""},
    {"vgetraw",		"VGETRAW"},
    {""},
    {"info",		"INFO"},
    {""}, {""}, {""}, {""},
    {"strlen",		"STRLEN"},
    {"ixtmget",	"IXMMGET"},
    {"MSET",		"MSET"},
    {""},
    {"geoget",		"GEOGET"},
    {""},
    {"echo",		"ECHO"},
    {"mgreserve",	"MGRESERVE"},
    {""}, {""}, {""}, {""},
    {"incrby",		"INCR"},
    {""}, {""}, {""}, {""},
    {"ttl",		"TTL"},
    {""}, {""}, {""},
    {"hget",		"HGET"},
    {""},
    {"CBFADD",		"CBFADD"},
    {"hgetall",	"HGETALL"},
    {""},
    {"xrcount",	"XRCOUNT"},
    {"xrexpire",	"XREXPIRE"},
    {""},
    {"xrexpireay",	"XREXPIREAT"},
    {"decrto",		"DECRTO"},
    {""},
    {"incrlimit",	"INCRLIMIT"},
    {"movenx",		"RENAMENX"},
    {"idel",		"IDEL"},
    {""},
    {"CMSREM",		"CMSREM"},
    {"hgetvals",	"HGETVALS"},
    {""}, {""},
    {"CMSRESERVE",	"CMSRESERVE"},
    {""}, {""},
    {"dbsizemutable",	"DBSIZEMUTABLE"},
    {"sladdpack",	"SLADDPACK"},
    {""},
    {"IXMADD",		"IXMADD"},
    {""}, {""},
    {"xrlast",		"XRLAST"},
    {""},
    {"vgetblob",		"VGETRAW"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {"IX5RANGE",	"IX5RANGE"},
    {""}, {""}, {""}, {""}, {""},
    {"mgincr",		"MGADD"},
    {"xnmin",		"XNMIN"},
    {"IX4RANGE",	"IX4RANGE"},
    {"vsimflat",		"VSIMFLAT"},
    {""},
    {"georemove",	"GEOREM"},
    {""},
    {"rblen",		"RBCOUNT"},
    {"reload",			"RELOAD"},
    {"rename",		"RENAME"},
    {""},
    {"tdinfo",			"TDINFO"},
    {"pfadd",		"PFADD"},
    {"pferror",	"PFERROR"},
    {""}, {""}, {""}, {""}, {""}, {""},
    {"exists",		"EXISTS"},
    {""}, {""},
    {"sladdshort",	"SLADDPACK"},
    {""}, {""}, {""}, {""}, {""}, {""},
    {"pfmerge",	"PFMERGE"},
    {"CMSINCR",	"CMSADD"},
    {""},
    {"CMSINCRBY",	"CMSADD"},
    {""},
    {"mhrem",		"MHREM"},
    {""}, {""}, {""}, {""},
    {"QUIT",		"EXIT"},
    {"hhdecr",		"HHDECR"},
    {""},
    {"MAXKEYSIZE",	"MAXKEYSIZE"},
    {"CFMADD",		"CFMADD"},
    {"xravg",		"XRAVG"},
    {"vgetnorm",		"VGETNORMALIZED"},
    {"ixhget",		"IXMGET"},
    {"ixtadd_utf8",		"IXTADD_UTF8"},
    {""},
    {"rbget",		"RBGET"},
    {"IX5REM",		"IX5REM"},
    {"vgetnormalized",		"VGETNORMALIZED"},
    {"geomget",	"GEOMGET"},
    {""},
    {"rsget",		"RSGET"},
    {""}, {""}, {""},
    {"IX4REM",		"IX4REM"},
    {"ssget",		"SSGET"},
    {"ixmgetindexes",	"IXMGETINDEXES"},
    {"MSETNX",		"MSETNX"},
    {""}, {""},
    {"tdmpercentile",		"TDMPERCENTILE"},
    {""}, {""},
    {"renamenx",	"RENAMENX"},
    {""}, {""}, {""},
    {"ixtgetindexes",	"IXMGETINDEXES"},
    {""},
    {"xrpersist",	"XRPERSIST"},
    {"TTL",		"TTL"},
    {"mc4rem",		"MC4REM"},
    {"mc4add",		"MC4ADD"},
    {"slmget",		"SLMGET"},
    {"mc4range",	"MC4RANGE"},
    {""},
    {"sizeof",		"SIZEOF"},
    {"mc4del",		"MC4REM"},
    {"mc4rangeflat",	"MC4RANGENAIVE"},
    {"mc4rangenaive",	"MC4RANGENAIVE"},
    {""},
    {"CBFADDCOUNT",	"CBFADDCOUNT"},
    {""}, {""},
    {"MC4RANGE",	"MC4RANGE"},
    {"mc4score",	"MC4SCORE"},
    {"mc4decode",	"MC4DECODE"},
    {""},
    {"MC4RANGEFLAT",	"MC4RANGENAIVE"},
    {"MC4RANGENAIVE",	"MC4RANGENAIVE"},
    {""},
    {"vmdistance",		"VMDISTANCE"},
    {""},
    {"mhsim",		"MHSIM"},
    {"CMSREMCOUNT",	"CMSREMCOUNT"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {"xrget",		"XRGET"},
    {"ix5rem",		"IX5REM"},
    {"ix5add",		"IX5ADD"},
    {""},
    {"ix5range",	"IX5RANGE"},
    {""}, {""},
    {"ixhremove",	"IXMREM"},
    {""},
    {"ix4rem",		"IX4REM"},
    {"ix4add",		"IX4ADD"},
    {"mhoverlap",	"MHOVERLAP"},
    {"ix4range",	"IX4RANGE"},
    {""}, {""},
    {"IX3RANGE",	"IX3RANGE"},
    {""},
    {"TOUCH",		"TOUCH"},
    {""}, {""}, {""},
    {"expire",		"EXPIRE"},
    {"imget",		"IMGET"},
    {""}, {""},
    {"DECR",		"DECR"},
    {""},
    {"ix5mexists",	"MEXISTS"},
    {"DECRBY",		"DECR"},
    {""}, {""}, {""}, {""}, {""}, {""},
    {"ix4mexists",	"MEXISTS"},
    {""}, {""},
    {"murmur",		"MURMUR"},
    {"MC4REM",		"MC4REM"},
    {""}, {""},
    {"touch",		"TOUCH"},
    {"RBLEN",		"RBCOUNT"},
    {"RELOAD",			"RELOAD"},
    {"murmurhash64a",	"MURMUR"},
    {""},
    {"igetkeys",	"IGETKEYS"},
    {""}, {""},
    {"cbfcount",	"CBFCOUNT"},
    {"expireat",	"EXPIREAT"},
    {""},
    {"georadius",	"GEORADIUS"},
    {"hdel",		"HDEL"},
    {"ixhmget",	"IXMMGET"},
    {"georadius_ro",	"GEORADIUS"},
    {"hdelall",	"HDELALL"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {"hmset",		"HMSET"},
    {""}, {""}, {""},
    {"cmscount",	"CMSCOUNT"},
    {""},
    {"RBRESERVE",	"RBRESERVE"},
    {"IX3REM",		"IX3REM"},
    {""}, {""},
    {"bitcount",	"BITCOUNT"},
    {"vdist",			"VDISTANCE"},
    {""}, {""}, {""}, {""},
    {"CAS",	"CAS"},
    {""}, {""}, {""},
    {"mc4encode",	"MC4ENCODE"},
    {""},
    {"expiretime",	"EXPIRETIME"},
    {""},
    {"mc3rem",		"MC3REM"},
    {"mc3add",		"MC3ADD"},
    {"xrsum",		"XRSUM"},
    {"mc3range",	"MC3RANGE"},
    {""}, {""},
    {"mc3del",		"MC3REM"},
    {"mc3rangeflat",	"MC3RANGENAIVE"},
    {"mc3rangenaive",	"MC3RANGENAIVE"},
    {"xncount",	"XNCOUNT"},
    {"xnexpire",	"XNEXPIRE"},
    {""},
    {"xnexpireat",	"XNEXPIREAT"},
    {"MC3RANGE",	"MC3RANGE"},
    {"mc3score",	"MC3SCORE"},
    {"mc3decode",	"MC3DECODE"},
    {""},
    {"MC3RANGEFLAT",	"MC3RANGENAIVE"},
    {"MC3RANGENAIVE",	"MC3RANGENAIVE"},
    {"GET",		"GET"},
    {"IGET",		"IGET"},
    {"GETX",		"XNGET"},
    {""},
    {"IGETALL",	"IGETALL"},
    {"XRDEL",		"XRDEL"},
    {"IXTDEL",		"IXMREM"},
    {"mgget",		"MGGET"},
    {""},
    {"DECRLIMIT",	"DECRLIMIT"},
    {"GETRANGE",	"GETRANGE"},
    {"mhbits",		"MHBITS"},
    {""},
    {"xnlast",		"XNLAST"},
    {""}, {""},
    {"mc4get",		"MC4GET"},
    {"VREM",			"VREM"},
    {"HEXISTS",	"HEXISTS"},
    {""}, {""},
    {"ix3rem",		"IX3REM"},
    {"ix3add",		"IX3ADD"},
    {"IXTREMOVE",	"IXMREM"},
    {"ix3range",	"IX3RANGE"},
    {""}, {""},
    {"BFRESERVE",	"BFRESERVE"},
    {"CFRESERVE",	"CFRESERVE"},
    {""}, {""}, {""}, {""},
    {"TDMEAN",			"TDMEAN"},
    {"vdistance",		"VDISTANCE"},
    {""},
    {"random",		"RANDOM"},
    {""}, {""}, {""}, {""},
    {"getpersist",	"GETPERSIST"},
    {"pfreserve",	"PFRESERVE"},
    {"CBFDECR",	"CBFREM"},
    {""},
    {"CBFDECRBY",	"CBFREM"},
    {"incrto",		"INCRTO"},
    {"ix3mexists",	"MEXISTS"},
    {"IXHREM",		"IXMREM"},
    {""}, {""},
    {"MC3REM",		"MC3REM"},
    {""},
    {"RBCOUNT",	"RBCOUNT"},
    {"XRCOUNT",	"XRCOUNT"},
    {""},
    {"INCR",		"INCR"},
    {""}, {""},
    {"INCRBY",		"INCR"},
    {"ixhadd_utf8",	"IXHADD_UTF8"},
    {""},
    {"BITGET",		"BITGET"},
    {"IXTGET",		"IXMGET"},
    {"hhreserve",	"HHRESERVE"},
    {"IXMDEL",		"IXMREM"},
    {"EXISTS",		"EXISTS"},
    {""},
    {"CMSADD",		"CMSADD"},
    {"RESET",		"RESET"},
    {""}, {""}, {""}, {""}, {""},
    {"xnavg",		"XNAVG"},
    {"slcount",	"SLCOUNT"},
    {""}, {""},
    {"tdpercentile",		"TDPERCENTILE"},
    {""}, {""},
    {"IXMREMOVE",	"IXMREM"},
    {"mc4remove",	"MC4REM"},
    {"ixhgetindexes",	"IXMGETINDEXES"},
    {""}, {""},
    {"quit",		"EXIT"},
    {"MGET",		"MGET"},
    {"mhmoverlap",	"MHMOVERLAP"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {"mc3encode",	"MC3ENCODE"},
    {""},
    {"BITMGET",	"BITMGET"},
    {"IXTMGET",	"IXMMGET"},
    {""}, {""}, {""},
    {"xnpersist",	"XNPERSIST"},
    {"hpersistall",	"HPERSISTALL"},
    {""},
    {"hmget",		"HMGET"},
    {""}, {""}, {""},
    {"ECHO",		"ECHO"},
    {""},
    {"XNEXPIRE",	"XNEXPIRE"},
    {""},
    {"XNEXPIREAT",	"XNEXPIREAT"},
    {""}, {""}, {""},
    {"pfoverlap",	"PFOVERLAP"},
    {"mhgetindexes",	"MHGETINDEXES"},
    {""},
    {"IXMGET",		"IXMGET"},
    {"hhincr",		"HHINCR"},
    {""}, {""},
    {"CFREM",		"CFREM"},
    {""}, {""}, {""}, {""},
    {"mc4mget",	"MC4MGET"},
    {"hgetkeys",	"HGETKEYS"},
    {""}, {""}, {""},
    {"mc3get",		"MC3GET"},
    {"xnget",		"XNGET"},
    {""}, {""}, {""},
    {"MOVE",		"RENAME"},
    {""}, {""},
    {"SUM",		"SUM"},
    {""}, {""}, {""},
    {"INCRLIMIT",	"INCRLIMIT"},
    {"IX5ADD",		"IX5ADD"},
    {""},
    {"TDMIN",			"TDMIN"},
    {""}, {""}, {""}, {""},
    {"IX6RANGE",	"IX6RANGE"},
    {"IX4ADD",		"IX4ADD"},
    {""},
    {"IXMMGET",	"IXMMGET"},
    {""}, {""}, {""},
    {"GEOREM",		"GEOREM"},
    {""},
    {"SETBIT",		"BITSET"},
    {""}, {""},
    {"IXTADD_UTF8",		"IXTADD_UTF8"},
    {""},
    {"ACRANGE",		"ACRANGE"},
    {""}, {""},
    {"pfset",		"PFSET"},
    {"thmquantile",		"TDMPERCENTILE"},
    {""},
    {"pfcount",	"PFCOUNT"},
    {""}, {""},
    {"pfaddcount",	"PFADDCOUNT"},
    {"sllen",		"SLCOUNT"},
    {""}, {""},
    {"dump",		"DUMP"},
    {""},
    {"hlen",		"HLEN"},
    {""},
    {"ACRANGE_BIN",		"ACRANGE"},
    {"ACRANGE_UTF8",		"ACRANGE"},
    {""},
    {"rbpush",		"RBADD"},
    {""}, {""}, {""}, {""}, {""}, {""},
    {"CMSADDCOUNT",	"CMSADDCOUNT"},
    {""}, {""}, {""}, {""},
    {"STRLEN",		"STRLEN"},
    {"mc3remove",	"MC3REM"},
    {"BFEXISTS",	"BFEXISTS"},
    {"CFEXISTS",	"CFEXISTS"},
    {""}, {""},
    {"XRLAST",		"XRLAST"},
    {""}, {""}, {""},
    {"rbpop",		"RBPOP"},
    {"IX6REM",		"IX6REM"},
    {""}, {""},
    {"shutdown",	"SHUTDOWN"},
    {""},
    {"DBSIZE",		"DBSIZE"},
    {""}, {""}, {""},
    {"rsgetcount",	"RSGETCOUNT"},
    {"slget",		"SLGET"},
    {""}, {""}, {""},
    {"pfbits",		"PFBITS"},
    {"xnsum",		"XNSUM"},
    {""},
    {"IX5MEXISTS",	"MEXISTS"},
    {"ssgetall",	"SSGETALL"},
    {""}, {""}, {""}, {""}, {""}, {""},
    {"IX4MEXISTS",	"MEXISTS"},
    {""}, {""}, {""}, {""},
    {"INFO",		"INFO"},
    {"MC4ADD",		"MC4ADD"},
    {"ping",		"PING"},
    {"TDSIZE",			"TDSIZE"},
    {""}, {""}, {""},
    {"BITCOUNT",	"BITCOUNT"},
    {"mc3mget",	"MC3MGET"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""},
    {"RSRESERVE",	"RSRESERVE"},
    {"MOVENX",		"RENAMENX"},
    {"XNMIN",		"XNMIN"},
    {"xuget",		"XUGET"},
    {"ix6rem",		"IX6REM"},
    {"ix6add",		"IX6ADD"},
    {""},
    {"ix6range",	"IX6RANGE"},
    {""}, {""}, {""},
    {"IX3ADD",		"IX3ADD"},
    {"listmaintainance",	"LISTMAINTAINANCE"},
    {""}, {""}, {""}, {""},
    {"CAD",	"CAD"},
    {""}, {""}, {""},
    {"CBFCOUNT",	"CBFCOUNT"},
    {""},
    {"RBADD",		"RBADD"},
    {""}, {""}, {""}, {""}, {""}, {""},
    {"ix6mexists",	"MEXISTS"},
    {""}, {""}, {""},
    {"ix5getindexes",	"IX5GETINDEXES"},
    {""},
    {"SSMERGE",	"SSMERGE"},
    {""}, {""},
    {"pfmoverlap",	"PFMOVERLAP"},
    {""}, {""},
    {"ix4getindexes",	"IX4GETINDEXES"},
    {""},
    {"IGETVALS",	"IGETVALS"},
    {""}, {""}, {""}, {""},
    {"VSIM",			"VSIM"},
    {""},
    {"HSET",		"HSET"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {"hlladd",		"PFADD"},
    {""}, {""},
    {"hllreserve",	"PFRESERVE"},
    {"hllset",		"PFSET"},
    {""}, {""},
    {"hllerror",	"PFERROR"},
    {""}, {""}, {""}, {""},
    {"TDMERGE",		"TDMERGE"},
    {""}, {""}, {""},
    {"TDMERGECAP",		"TDMERGECAPACITY"},
    {""}, {""}, {""},
    {"hhget",		"HHGET"},
    {"TDMERGECAPACITY",	"TDMERGECAPACITY"},
    {"hllmerge",	"PFMERGE"},
    {"thquantile",		"TDPERCENTILE"},
    {""}, {""}, {""}, {""},
    {"BFADD",		"BFADD"},
    {"CFADD",		"CFADD"},
    {""},
    {"RBPOP",		"RBPOP"},
    {""},
    {"IX3MEXISTS",	"MEXISTS"},
    {""}, {""},
    {"IXHADD",		"IXHADD_UTF8"},
    {""}, {""},
    {"MC3ADD",		"MC3ADD"},
    {"IXHADD_BIN",	"IXHADD_BIN"},
    {""}, {""}, {""},
    {"CMSDECR",	"CMSREM"},
    {"GETSET",		"GETSET"},
    {"CMSDECRBY",	"CMSREM"},
    {""},
    {"IX2RANGE",	"IX2RANGE"},
    {""}, {""},
    {"DECRTO",		"DECRTO"},
    {""}, {""},
    {"spop",	"SPOP"},
    {"append",		"APPEND"},
    {""}, {""}, {""}, {""}, {""},
    {"mc8rem",		"MC8REM"},
    {"mc8add",		"MC8ADD"},
    {""},
    {"mc8range",	"MC8RANGE"},
    {""},
    {"MAXVALSIZE",	"MAXVALSIZE"},
    {"mc8del",		"MC8REM"},
    {"mc8rangeflat",	"MC8RANGENAIVE"},
    {"mc8rangenaive",	"MC8RANGENAIVE"},
    {""}, {""}, {""}, {""},
    {"MC8RANGE",	"MC8RANGE"},
    {"mc8score",	"MC8SCORE"},
    {"mc8decode",	"MC8DECODE"},
    {""},
    {"MC8RANGEFLAT",	"MC8RANGENAIVE"},
    {"MC8RANGENAIVE",	"MC8RANGENAIVE"},
    {"hllmjaccard",	"PFMJACCARD"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {"DEL",		"DEL"},
    {"IDEL",		"IDEL"},
    {""}, {""},
    {"XNFIRST",	"XNFIRST"},
    {""},
    {"ix3getindexes",	"IX3GETINDEXES"},
    {""},
    {"IX2REM",		"IX2REM"},
    {"RBGET",		"RBGET"},
    {"XRGET",		"XRGET"},
    {""},
    {"ACREM",			"ACREM_UTF8"},
    {""},
    {"hlladdcount",	"PFADDCOUNT"},
    {""},
    {"ACREM_BIN",		"ACREM_BIN"},
    {""}, {""}, {""}, {""}, {""},
    {"TDQUANTILE",		"TDPERCENTILE"},
    {""}, {""},
    {"mc2rem",		"MC2REM"},
    {"mc2add",		"MC2ADD"},
    {""},
    {"mc2range",	"MC2RANGE"},
    {""}, {""},
    {"mc2del",		"MC2REM"},
    {"mc2rangeflat",	"MC2RANGENAIVE"},
    {"mc2rangenaive",	"MC2RANGENAIVE"},
    {"MC8REM",		"MC8REM"},
    {""}, {""}, {""},
    {"MC2RANGE",	"MC2RANGE"},
    {"mc2score",	"MC2SCORE"},
    {"mc2decode",	"MC2DECODE"},
    {""},
    {"MC2RANGEFLAT",	"MC2RANGENAIVE"},
    {"MC2RANGENAIVE",	"MC2RANGENAIVE"},
    {"count",		"COUNT"},
    {"ACREM_UTF8",		"ACREM_UTF8"},
    {""}, {""}, {""}, {""}, {""},
    {"unlink",		"DEL"},
    {""}, {""},
    {"GEOADD",		"GEOADD"},
    {"IXTEXISTS",	"EXISTS"},
    {""}, {""}, {""}, {""},
    {"pfintersect",	"PFINTERSECT"},
    {""}, {""}, {""}, {""},
    {"ix2rem",		"IX2REM"},
    {"ix2add",		"IX2ADD"},
    {""},
    {"ix2range",	"IX2RANGE"},
    {""}, {""}, {""}, {""},
    {"hllintersect",	"PFINTERSECT"},
    {""}, {""}, {""}, {""},
    {"EXPIRE",		"EXPIRE"},
    {"SIZEOF",		"SIZEOF"},
    {"mc8encode",	"MC8ENCODE"},
    {""},
    {"EXPIRETIME",	"EXPIRETIME"},
    {""}, {""}, {""}, {""},
    {"IX1RANGE",	"IX1RANGE"},
    {"TDTRIMMEDMEAN",		"TDTRIMMEDMEAN"},
    {""}, {""},
    {"ix2mexists",	"MEXISTS"},
    {""},
    {"INCRTO",		"INCRTO"},
    {""},
    {"MC2REM",		"MC2REM"},
    {"IMGET",		"IMGET"},
    {""},
    {"MRAND",		"MRANDOM"},
    {""},
    {"MRANDOM",	"MRANDOM"},
    {""}, {""}, {""},
    {"IX6ADD",		"IX6ADD"},
    {"MHBITS",		"MHBITS"},
    {""}, {""},
    {"EXPIREAT",	"EXPIREAT"},
    {""},
    {"GETBIT",		"BITGET"},
    {"uniqueid",	"UNIQUEID"},
    {""}, {""},
    {"IXMEXISTS",	"EXISTS"},
    {""}, {""}, {""}, {""},
    {"mc8get",		"MC8GET"},
    {""}, {""},
    {"MC4DEL",		"MC4REM"},
    {"ACRANGEALL",		"ACRANGEALL"},
    {""}, {""}, {""},
    {"ACRANGEALL_BIN",		"ACRANGEALL"},
    {"ACRANGEALL_UTF8",	"ACRANGEALL"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {"MURMUR",		"MURMUR"},
    {"GEORADIUS",	"GEORADIUS"},
    {""},
    {"MC4REMOVE",	"MC4REM"},
    {"GEORADIUS_RO",	"GEORADIUS"},
    {"mc2encode",	"MC2ENCODE"},
    {"PFERROR",	"PFERROR"},
    {""},
    {"IX1REM",		"IX1REM"},
    {""}, {""},
    {"SSRESERVE",	"SSRESERVE"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {"slpush",		"SLADD"},
    {""}, {""}, {""},
    {"slpushpack",	"SLADDPACK"},
    {"mc1rem",		"MC1REM"},
    {"mc1add",		"MC1ADD"},
    {""},
    {"mc1range",	"MC1RANGE"},
    {""}, {""},
    {"mc1del",		"MC1REM"},
    {""}, {""},
    {"RSADD",		"RSADD"},
    {""}, {""}, {""},
    {"MC1RANGE",	"MC1RANGE"},
    {"mc1score",	"MC1SCORE"},
    {""},
    {"BFMEXISTS",	"BFMEXISTS"},
    {"CFMEXISTS",	"CFMEXISTS"},
    {"MC4GET",		"MC4GET"},
    {"mc2get",		"MC2GET"},
    {""},
    {"TDRESERVE",		"TDRESERVE"},
    {"SAVE",			"SAVE"},
    {""},
    {"IX6MEXISTS",	"MEXISTS"},
    {"mc8remove",	"MC8REM"},
    {"slgetall",	"SLGETALL"},
    {""}, {""},
    {"MC4ENCODE",	"MC4ENCODE"},
    {"CMSCOUNT",	"CMSCOUNT"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {"ix1rem",		"IX1REM"},
    {"ix1add",		"IX1ADD"},
    {""},
    {"ix1range",	"IX1RANGE"},
    {""},
    {"VGET",			"VGET"},
    {""}, {""}, {""}, {""},
    {"VGETBLOB",		"VGETRAW"},
    {""}, {""}, {""}, {""},
    {"MC4MGET",	"MC4MGET"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {"BGSAVE",			"SAVE"},
    {""},
    {"ix1mexists",	"MEXISTS"},
    {""},
    {"PFMERGE",	"PFMERGE"},
    {""},
    {"MC1REM",		"MC1REM"},
    {""},
    {"VMDIST",			"VMDISTANCE"},
    {"mc8mget",	"MC8MGET"},
    {""}, {""}, {""}, {""},
    {"IXHDEL",		"IXMREM"},
    {"ACADD",			"ACADD_UTF8"},
    {""},
    {"MC3DEL",		"MC3REM"},
    {""},
    {"ACADD_BIN",		"ACADD_BIN"},
    {""}, {""},
    {"mc2remove",	"MC2REM"},
    {""}, {""}, {""}, {""}, {""}, {""},
    {"RBPUSH",		"RBADD"},
    {"ix6getindexes",	"IX6GETINDEXES"},
    {"IXHREMOVE",	"IXMREM"},
    {""},
    {"GETDEL",		"GETDEL"},
    {"MC3REMOVE",	"MC3REM"},
    {"DBSIZEMUTABLE",	"DBSIZEMUTABLE"},
    {""},
    {"HGET",		"HGET"},
    {""}, {""},
    {"HGETALL",	"HGETALL"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {"ACADD_UTF8",		"ACADD_UTF8"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {"PFBITS",		"PFBITS"},
    {""}, {""}, {""}, {""},
    {"mc2mget",	"MC2MGET"},
    {"IXHGET",		"IXMGET"},
    {""},
    {"MGRESERVE",	"MGRESERVE"},
    {"MC3GET",		"MC3GET"},
    {""}, {""}, {""}, {""}, {""},
    {"SSMGET",		"SSMGET"},
    {""}, {""},
    {"TDMQUANTILE",		"TDMPERCENTILE"},
    {""},
    {"MC3ENCODE",	"MC3ENCODE"},
    {"SELECT",		"SELECT"},
    {"RSGET",		"RSGET"},
    {""}, {""}, {""},
    {"mc1get",		"MC1GET"},
    {""}, {""}, {""}, {""},
    {"IX2ADD",		"IX2ADD"},
    {""},
    {"SLLEN",		"SLCOUNT"},
    {""}, {""},
    {"SETXX",		"SETXX"},
    {""},
    {"setbit",		"BITSET"},
    {""},
    {"SETEX",		"SETEX"},
    {""}, {""},
    {"IXHMGET",	"IXMMGET"},
    {""}, {""},
    {"MC3MGET",	"MC3MGET"},
    {""}, {""}, {""},
    {"XNDEL",		"XNDEL"},
    {""}, {""},
    {"VERSION",	"VERSION"},
    {""}, {""}, {""},
    {"MC8ADD",		"MC8ADD"},
    {""}, {""}, {""}, {""}, {""}, {""},
    {"GEODEL",		"GEOREM"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {"bfexists",	"BFEXISTS"},
    {""},
    {"tdtrimmedmean",		"TDTRIMMEDMEAN"},
    {""}, {""}, {""},
    {"MC4SCORE",	"MC4SCORE"},
    {""}, {""},
    {"GEOREMOVE",	"GEOREM"},
    {"MHMOVERLAP",	"MHMOVERLAP"},
    {""}, {""},
    {"TDMEDIAN",		"TDMEDIAN"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {"mc1remove",	"MC1REM"},
    {"XRPERSIST",	"XRPERSIST"},
    {""}, {""}, {""}, {""},
    {"XNCOUNT",	"XNCOUNT"},
    {""}, {""}, {""},
    {"IGETKEYS",	"IGETKEYS"},
    {""},
    {"XRSUM",		"XRSUM"},
    {""}, {""}, {""},
    {"hlloverlap",	"PFOVERLAP"},
    {""},
    {"IXHADD_UTF8",	"IXHADD_UTF8"},
    {"IX2MEXISTS",	"MEXISTS"},
    {"CBFMCOUNT",	"CBFMCOUNT"},
    {""},
    {"IXTGETINDEXES",	"IXMGETINDEXES"},
    {"hllmoverlap",	"PFMOVERLAP"},
    {""},
    {"MC2ADD",		"MC2ADD"},
    {"MHREM",		"MHREM"},
    {""},
    {"GEOGET",		"GEOGET"},
    {"HMSET",		"HMSET"},
    {"MSETXX",		"MSETXX"},
    {""}, {""},
    {"slpushshort",	"SLADDPACK"},
    {""}, {""}, {""}, {""},
    {"VGETNORM",		"VGETNORMALIZED"},
    {"GEOENCODE",	"GEOENCODE"},
    {""},
    {"cfexists",	"CFEXISTS"},
    {""}, {""},
    {"VGETNORMALIZED",		"VGETNORMALIZED"},
    {""}, {""}, {""},
    {"mc1mget",	"MC1MGET"},
    {""}, {""}, {""}, {""},
    {"mc4point",	"MC4POINT"},
    {""}, {""}, {""}, {""},
    {"SLCOUNT",	"SLCOUNT"},
    {""}, {""}, {""}, {""}, {""}, {""},
    {"GEOMGET",	"GEOMGET"},
    {"XRMAX",		"XRMAX"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {"IX1ADD",		"IX1ADD"},
    {""}, {""}, {""}, {""}, {""}, {""},
    {"IXMGETINDEXES",	"IXMGETINDEXES"},
    {""}, {""},
    {"XUGET",		"XUGET"},
    {""}, {""}, {""}, {""},
    {"ix2getindexes",	"IX2GETINDEXES"},
    {"SSADD",		"SSADD"},
    {""}, {""},
    {"hllcount",	"PFCOUNT"},
    {""},
    {"getbit",		"BITGET"},
    {""}, {""}, {""},
    {"SSADDMGET",	"SSADDMGET"},
    {""}, {""}, {""}, {""}, {""},
    {"MC3SCORE",	"MC3SCORE"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {"PFRESERVE",	"PFRESERVE"},
    {""},
    {"IX5EXISTS",	"EXISTS"},
    {""}, {""}, {""}, {""}, {""},
    {"SSADDGET",	"SSADDGET"},
    {""},
    {"IX4EXISTS",	"EXISTS"},
    {"SSADDGETALL",	"SSADDGETALL"},
    {"TDADD",			"TDADD"},
    {"SLMGET",		"SLMGET"},
    {""}, {""},
    {"VGETRAW",		"VGETRAW"},
    {""},
    {"TDADDWEIGHT",		"TDADDWEIGHT"},
    {"MURMURHASH64A",	"MURMUR"},
    {""},
    {"setex",		"SETEX"},
    {"HPERSISTALL",	"HPERSISTALL"},
    {""},
    {"version",	"VERSION"},
    {""}, {""}, {""}, {""}, {""}, {""},
    {"tdmax",			"TDMAX"},
    {""}, {""}, {""},
    {"msetxx",		"MSETXX"},
    {"bfmexists",	"BFMEXISTS"},
    {""}, {""}, {""}, {""}, {""},
    {"IX1MEXISTS",	"MEXISTS"},
    {""},
    {"GETPERSIST",	"GETPERSIST"},
    {""}, {""},
    {"XNLAST",		"XNLAST"},
    {"MC1ADD",		"MC1ADD"},
    {""}, {""}, {""}, {""}, {""},
    {"xrmax",		"XRMAX"},
    {""}, {""}, {""}, {""}, {""},
    {"mc3point",	"MC3POINT"},
    {"PFMOVERLAP",	"PFMOVERLAP"},
    {""}, {""},
    {"XRAVG",		"XRAVG"},
    {""}, {""},
    {"geodist",	"GEODIST"},
    {""}, {""}, {""}, {""}, {""}, {""},
    {"setxx",		"SETXX"},
    {"HGETVALS",	"HGETVALS"},
    {"mhjaccard",	"MHJACCARD"},
    {"TDMPERCENTILE",		"TDMPERCENTILE"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""},
    {"mhmjaccard",	"MHMJACCARD"},
    {""},
    {"PFCOUNT",	"PFCOUNT"},
    {""}, {""}, {""}, {""}, {""}, {""},
    {"MC4EXISTS",	"EXISTS"},
    {"cfmexists",	"CFMEXISTS"},
    {"VSIMFLAT",		"VSIMFLAT"},
    {""},
    {"PFSET",		"PFSET"},
    {""}, {""},
    {"GEOSCORE",	"GEOGET"},
    {""}, {""}, {""}, {""}, {""}, {""},
    {"PERSIST",	"PERSIST"},
    {"ix1getindexes",	"IX1GETINDEXES"},
    {""}, {""}, {""}, {""}, {""}, {""},
    {"SSGET",		"SSGET"},
    {""}, {""},
    {"RAND",		"RANDOM"},
    {"PERSISTEXPIRED",	"PERSISTDELETED"},
    {""}, {""}, {""}, {""},
    {"MGADD",		"MGADD"},
    {""},
    {"IX3EXISTS",	"EXISTS"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""},
    {"MHADD",		"MHADD"},
    {""}, {""},
    {"MHMJACCARD",	"MHMJACCARD"},
    {""}, {""},
    {"HLLRESERVE",	"PFRESERVE"},
    {""}, {""}, {""},
    {"MC8DEL",		"MC8REM"},
    {"ixmexists",	"EXISTS"},
    {""}, {""}, {""}, {""}, {""}, {""},
    {"MGADDGET",	"MGADDGET"},
    {""}, {""}, {""},
    {"ixtexists",	"EXISTS"},
    {""}, {""}, {""},
    {"UNIQID",		"UNIQUEID"},
    {"MC8REMOVE",	"MC8REM"},
    {""}, {""},
    {"getex",		"GETEX"},
    {"HLLMJACCARD",	"PFMJACCARD"},
    {"getexat",	"GETEXAT"},
    {""}, {""}, {""},
    {"COUNT",		"COUNT"},
    {""}, {""}, {""},
    {"SLADD",		"SLADD"},
    {""}, {""}, {""}, {""},
    {"SLADDPACK",	"SLADDPACK"},
    {""},
    {"HDEL",		"HDEL"},
    {""}, {""},
    {"HDELALL",	"HDELALL"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {"GETEX",		"GETEX"},
    {""},
    {"GETEXAT",	"GETEXAT"},
    {""}, {""}, {""}, {""},
    {"MC8GET",		"MC8GET"},
    {"HLLINTERSECT",	"PFINTERSECT"},
    {"vgetindexes",		"VGETINDEXES"},
    {"MHSIM",		"MHSIM"},
    {"MC2DEL",		"MC2REM"},
    {""}, {""}, {""}, {""},
    {"MC3EXISTS",	"EXISTS"},
    {""},
    {"MC8ENCODE",	"MC8ENCODE"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {"UNLINK",		"DEL"},
    {""},
    {"MC2REMOVE",	"MC2REM"},
    {""}, {""}, {""},
    {"CMSMCOUNT",	"CMSMCOUNT"},
    {""}, {""}, {""},
    {"HLLMERGE",	"PFMERGE"},
    {""}, {""}, {""}, {""},
    {"MC4DECODE",	"MC4DECODE"},
    {""}, {""},
    {"MC8MGET",	"MC8MGET"},
    {""}, {""}, {""}, {""}, {""},
    {"VGETINDEXES",		"VGETINDEXES"},
    {""}, {""}, {""}, {""}, {""},
    {"XRNEXT",		"XRNEXT"},
    {""}, {""}, {""}, {""},
    {"setnx",		"SETNX"},
    {""}, {""}, {""}, {""}, {""}, {""},
    {"MC2GET",		"MC2GET"},
    {"MGGET",		"MGGET"},
    {"XNGET",		"XNGET"},
    {""},
    {"RENAME",		"RENAME"},
    {""}, {""},
    {"RENAMENX",	"RENAMENX"},
    {""},
    {"RSGETCOUNT",	"RSGETCOUNT"},
    {""},
    {"MC2ENCODE",	"MC2ENCODE"},
    {"SADD",	"SADD"},
    {""},
    {"HMGET",		"HMGET"},
    {""}, {""}, {""},
    {"xrnext",		"XRNEXT"},
    {""}, {""},
    {"persist",	"PERSIST"},
    {""},
    {"pfjaccard",	"PFJACCARD"},
    {""}, {""}, {""}, {""}, {""}, {""},
    {"xnmax",		"XNMAX"},
    {""},
    {"persistexpired",	"PERSISTDELETED"},
    {""},
    {"persistdeleted",	"PERSISTDELETED"},
    {"pfmjaccard",	"PFMJACCARD"},
    {""},
    {"MC2MGET",	"MC2MGET"},
    {""}, {""}, {""},
    {"SLADDSHORT",	"SLADDPACK"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""},
    {"SLGET",		"SLGET"},
    {"GEODIST",	"GEODIST"},
    {""},
    {"PFADD",		"PFADD"},
    {""}, {""},
    {"PFMJACCARD",	"PFMJACCARD"},
    {""}, {""},
    {"HLEN",		"HLEN"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {"MHOVERLAP",	"MHOVERLAP"},
    {""}, {""}, {""}, {""}, {""},
    {"MC1DEL",		"MC1REM"},
    {""}, {""}, {""},
    {"IX5GETINDEXES",	"IX5GETINDEXES"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {"IX4GETINDEXES",	"IX4GETINDEXES"},
    {""},
    {"MC3DECODE",	"MC3DECODE"},
    {""}, {""},
    {"MC1REMOVE",	"MC1REM"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""},
    {"IX6EXISTS",	"EXISTS"},
    {""},
    {"VDIST",			"VDISTANCE"},
    {""}, {""}, {""}, {""},
    {"VDISTANCE",		"VDISTANCE"},
    {""}, {""},
    {"HLLERROR",	"PFERROR"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {"MC8SCORE",	"MC8SCORE"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {"MC1GET",		"MC1GET"},
    {""}, {""}, {""}, {""}, {""},
    {"HHRESERVE",	"HHRESERVE"},
    {""}, {""}, {""}, {""},
    {"TYPE",		"TYPE"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""},
    {"DUMP",		"DUMP"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""},
    {"MC1MGET",	"MC1MGET"},
    {""}, {""}, {""},
    {"HLLSET",		"PFSET"},
    {""}, {""}, {""},
    {"TDINFO",			"TDINFO"},
    {""}, {""}, {""}, {""}, {""},
    {"HLLADD",		"PFADD"},
    {""},
    {"MC2SCORE",	"MC2SCORE"},
    {""}, {""}, {""}, {""}, {""}, {""},
    {"mc8point",	"MC8POINT"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {"GEODECODE",	"GEODECODE"},
    {""}, {""}, {""}, {""}, {""},
    {"IX3GETINDEXES",	"IX3GETINDEXES"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""},
    {"type",		"TYPE"},
    {""},
    {"VMDISTANCE",		"VMDISTANCE"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {"COPY",		"COPY"},
    {"MGINCR",		"MGADD"},
    {""},
    {"mc16add",	"MC16ADD"},
    {""}, {""}, {""},
    {"mc16del",	"MC16REM"},
    {"mc16rem",	"MC16REM"},
    {""}, {""}, {""},
    {"MC16ADD",	"MC16ADD"},
    {""},
    {"mc16exists",	"EXISTS"},
    {""}, {""},
    {"MC16DEL",	"MC16REM"},
    {"mc2point",	"MC2POINT"},
    {"PFOVERLAP",	"PFOVERLAP"},
    {""}, {""}, {""}, {""},
    {"xnnext",		"XNNEXT"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {"mc16score",	"MC16SCORE"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {"MC16SCORE",	"MC16SCORE"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""},
    {"IXHGETINDEXES",	"IXMGETINDEXES"},
    {""}, {""}, {""},
    {"SLPUSH",		"SLADD"},
    {""}, {""}, {""}, {""}, {""},
    {"mc4exists",	"EXISTS"},
    {""}, {""},
    {"xrgetkeys",	"XRGETKEYS"},
    {""}, {""},
    {"HGETKEYS",	"HGETKEYS"},
    {""}, {""}, {""}, {""},
    {"HLLADDCOUNT",	"PFADDCOUNT"},
    {"SETNX",		"SETNX"},
    {""}, {""},
    {"SPOP",	"SPOP"},
    {""}, {""}, {""},
    {"TDMAX",			"TDMAX"},
    {"MC1SCORE",	"MC1SCORE"},
    {""},
    {"IX2EXISTS",	"EXISTS"},
    {""}, {""}, {""},
    {"hexpireall",	"HEXPIREALL"},
    {""},
    {"hexpireatall",	"HEXPIREATALL"},
    {""}, {""},
    {"VADD",			"VADD"},
    {"ix5exists",	"EXISTS"},
    {""}, {""},
    {"HLLBITS",	"PFBITS"},
    {""}, {""}, {""}, {""},
    {"ix4exists",	"EXISTS"},
    {""}, {""},
    {"SHUTDOWN",	"SHUTDOWN"},
    {""}, {""}, {""}, {""},
    {"MC8EXISTS",	"EXISTS"},
    {"mc16encode",	"MC16ENCODE"},
    {"mc16decode",	"MC16DECODE"},
    {"mc16remove",	"MC16REM"},
    {""}, {""}, {""},
    {"SSGETALL",	"SSGETALL"},
    {"XRGETKEYS",	"XRGETKEYS"},
    {""},
    {"copy",		"COPY"},
    {""},
    {"COPYNX",		"COPYNX"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""},
    {"XNPERSIST",	"XNPERSIST"},
    {""}, {""}, {""}, {""}, {""}, {""},
    {"MC16DECODE",	"MC16DECODE"},
    {""}, {""}, {""},
    {"XNSUM",		"XNSUM"},
    {""}, {""}, {""}, {""}, {""},
    {"mc1point",	"MC1POINT"},
    {""},
    {"xunext",		"XUNEXT"},
    {"APPEND",		"APPEND"},
    {""}, {""}, {""},
    {"MHJACCARD",	"MHJACCARD"},
    {""}, {""}, {""},
    {"mc16range",	"MC16RANGE"},
    {""}, {""}, {""},
    {"mc16rangeflat",	"MC16RANGENAIVE"},
    {"mc16rangenaive",	"MC16RANGENAIVE"},
    {""}, {""}, {""}, {""},
    {"MC2EXISTS",	"EXISTS"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""},
    {"mc3exists",	"EXISTS"},
    {""}, {""}, {""},
    {"PING",		"PING"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""},
    {"XNMAX",		"XNMAX"},
    {"MC16ENCODE",	"MC16ENCODE"},
    {""}, {""},
    {"XUNEXT",		"XUNEXT"},
    {""},
    {"HLLOVERLAP",	"PFOVERLAP"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""},
    {"IX6GETINDEXES",	"IX6GETINDEXES"},
    {""},
    {"PERSISTDELETED",	"PERSISTDELETED"},
    {"IX1EXISTS",	"EXISTS"},
    {""},
    {"ix3exists",	"EXISTS"},
    {""}, {""}, {""}, {""}, {""},
    {"copynx",		"COPYNX"},
    {""}, {""}, {""},
    {"LISTMAINTAINANCE",	"LISTMAINTAINANCE"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {"MC4POINT",	"MC4POINT"},
    {""}, {""}, {""}, {""},
    {"mc16get",	"MC16GET"},
    {"MC8DECODE",	"MC8DECODE"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {"mc16mget",	"MC16MGET"},
    {""}, {""},
    {"PFADDCOUNT",	"PFADDCOUNT"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""},
    {"uniqid",		"UNIQUEID"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""},
    {"hllbits",	"PFBITS"},
    {""},
    {"MC1EXISTS",	"EXISTS"},
    {"hlljaccard",	"PFJACCARD"},
    {"XNAVG",		"XNAVG"},
    {"xngetkeys",	"XNGETKEYS"},
    {"MC16REM",	"MC16REM"},
    {""}, {""}, {""}, {""},
    {"MC2DECODE",	"MC2DECODE"},
    {""}, {""}, {""}, {""},
    {"SLGETALL",	"SLGETALL"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""},
    {"PFJACCARD",	"PFJACCARD"},
    {""}, {""}, {""}, {""},
    {"PFINTERSECT",	"PFINTERSECT"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {"HEXPIREALL",	"HEXPIREALL"},
    {""},
    {"HEXPIREATALL",	"HEXPIREATALL"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {"HHGET",		"HHGET"},
    {"UNIQUEID",	"UNIQUEID"},
    {"MC3POINT",	"MC3POINT"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {"MC16EXISTS",	"EXISTS"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""},
    {"MHGETINDEXES",	"MHGETINDEXES"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""},
    {"SLPUSHPACK",	"SLADDPACK"},
    {""},
    {"IX2GETINDEXES",	"IX2GETINDEXES"},
    {""}, {""}, {""},
    {"MC16REMOVE",	"MC16REM"},
    {""}, {""}, {""},
    {"xugetkeys",	"XUGETKEYS"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""},
    {"HHDECR",		"HHDECR"},
    {""}, {""}, {""},
    {"ix6exists",	"EXISTS"},
    {"HLLJACCARD",	"PFJACCARD"},
    {"TDPERCENTILE",		"TDPERCENTILE"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""},
    {"HLLCOUNT",	"PFCOUNT"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""},
    {"XNNEXT",		"XNNEXT"},
    {"RANDOM",		"RANDOM"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""},
    {"HLLMOVERLAP",	"PFMOVERLAP"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {"mc16point",	"MC16POINT"},
    {""},
    {"IX1GETINDEXES",	"IX1GETINDEXES"},
    {""}, {""}, {""}, {""},
    {"XUGETKEYS",	"XUGETKEYS"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""},
    {"mc8exists",	"EXISTS"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {"HHINCR",		"HHINCR"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""},
    {"mc2exists",	"EXISTS"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""},
    {"ix2exists",	"EXISTS"},
    {""}, {""},
    {"MC16GET",	"MC16GET"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {"SLPUSHSHORT",	"SLADDPACK"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""},
    {"MC8POINT",	"MC8POINT"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {"mc1exists",	"EXISTS"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {"MC16MGET",	"MC16MGET"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""},
    {"MC16POINT",	"MC16POINT"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""},
    {"ix1exists",	"EXISTS"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""},
    {"MC2POINT",	"MC2POINT"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""},
    {"XNGETKEYS",	"XNGETKEYS"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""},
    {"MC1POINT",	"MC1POINT"},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""},
    {"MC16RANGE",	"MC16RANGE"},
    {""}, {""}, {""},
    {"MC16RANGEFLAT",	"MC16RANGENAIVE"},
    {"MC16RANGENAIVE",	"MC16RANGENAIVE"}
  };
#if (defined __GNUC__ && __GNUC__ + (__GNUC_MINOR__ >= 6) > 4) || (defined __clang__ && __clang_major__ >= 3)
#pragma GCC diagnostic pop
#endif

struct data *
CommandPerfectHash::in_word_set (const char *str, size_t len)
{
  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH)
    {
      unsigned int key = hash (str, len);

      if (key <= MAX_HASH_VALUE)
        {
          const char *s = wordlist[key].name;

          if (*str == *s && !strncmp (str + 1, s + 1, len - 1) && s[len] == '\0')
            return &wordlist[key];
        }
    }
  return static_cast<struct data *> (0);
}

} // net::worker::commands::gperf
#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic pop
#endif
